<template>
  <Card dis-hover>
    <template #title>
      <Space>
        <span>My File Library</span>
        <Button size="small" :loading="loading" @click="loadFiles">Refresh</Button>
      </Space>
    </template>

    <Alert type="info" show-icon style="margin-bottom: 12px">
      Files generated by agent/skill responses are stored per user account and can be downloaded here. Upload your own files first if a skill needs input data.
    </Alert>

    <div class="upload-bar">
      <input ref="fileInput" type="file" multiple hidden @change="onSelectFiles" />
      <Button type="primary" ghost @click="pickFiles">Choose Files</Button>
      <Button :disabled="selectedFiles.length === 0" :loading="uploading" type="primary" @click="uploadFiles">
        Upload Selected
      </Button>
      <span class="upload-hint">{{ uploadHint }}</span>
    </div>

    <div v-if="selectedFiles.length" class="selected-list">
      <Tag v-for="file in selectedFiles" :key="fileKey(file)" color="gold">{{ file.name }}</Tag>
    </div>

    <Table :columns="columns" :data="files" stripe :loading="loading">
      <template #size="{ row }">
        {{ formatSize(row.size_bytes) }}
      </template>
      <template #updated="{ row }">
        {{ row.updated_at ? new Date(row.updated_at).toLocaleString() : "-" }}
      </template>
      <template #action="{ row }">
        <Button size="small" type="primary" ghost :loading="downloadingPath === row.path" @click="downloadFile(row)">
          Download
        </Button>
      </template>
    </Table>

    <div v-if="!loading && files.length === 0" style="text-align:center; color:#999; padding: 24px 0;">
      No files yet. Ask agent to generate content with skills, then come back here.
    </div>
  </Card>
</template>

<script setup>
import { computed, onMounted, ref } from "vue";
import { Message } from "view-ui-plus";
import { api } from "../services/api";

const loading = ref(false);
const uploading = ref(false);
const files = ref([]);
const downloadingPath = ref("");
const selectedFiles = ref([]);
const fileInput = ref(null);

const columns = [
  { title: "Path", key: "path", minWidth: 420 },
  { title: "Size", slot: "size", width: 120 },
  { title: "Updated", slot: "updated", width: 210 },
  { title: "Action", slot: "action", width: 120, align: "center" },
];

function formatSize(bytes) {
  const size = Number(bytes || 0);
  if (size < 1024) return `${size} B`;
  if (size < 1024 * 1024) return `${(size / 1024).toFixed(1)} KB`;
  return `${(size / 1024 / 1024).toFixed(1)} MB`;
}

const uploadHint = computed(() => {
  if (!selectedFiles.value.length) return "Select one or more files, then upload them to your personal file library.";
  if (selectedFiles.value.length === 1) return `Ready to upload 1 file: ${selectedFiles.value[0].name}`;
  return `Ready to upload ${selectedFiles.value.length} files.`;
});

function fileKey(file) {
  return `${file.name}-${file.size}-${file.lastModified}`;
}

function pickFiles() {
  fileInput.value?.click();
}

function onSelectFiles(event) {
  const nextFiles = Array.from(event.target.files || []);
  selectedFiles.value = nextFiles;
  event.target.value = "";
}

async function uploadFiles() {
  if (!selectedFiles.value.length) return;

  uploading.value = true;
  try {
    const response = await api.uploadMyFiles(selectedFiles.value);
    Message.success(`Uploaded ${response.count || selectedFiles.value.length} file(s)`);
    selectedFiles.value = [];
    await loadFiles();
  } catch (error) {
    Message.error(error.message || "Upload failed");
  } finally {
    uploading.value = false;
  }
}

async function loadFiles() {
  loading.value = true;
  try {
    const response = await api.listMyFiles();
    files.value = response.files || [];
  } catch (error) {
    Message.error(error.message || "Failed to load files");
  } finally {
    loading.value = false;
  }
}

async function downloadFile(row) {
  downloadingPath.value = row.path;
  try {
    const response = await api.downloadMyFile(row.path);
    if (!response.ok) {
      const text = await response.text();
      throw new Error(text || `Download failed (${response.status})`);
    }

    const blob = await response.blob();
    const disposition = response.headers.get("content-disposition") || "";
    const match = /filename="?([^";]+)"?/i.exec(disposition);
    const filename = match?.[1] || row.path.split("/").pop() || "download.bin";

    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  } catch (error) {
    Message.error(error.message || "Download failed");
  } finally {
    downloadingPath.value = "";
  }
}

onMounted(loadFiles);
</script>

<style scoped>
.upload-bar {
  display: flex;
  align-items: center;
  gap: 10px;
  flex-wrap: wrap;
  margin-bottom: 12px;
}

.upload-hint {
  color: #888;
  font-size: 12px;
}

.selected-list {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
  margin-bottom: 12px;
}
</style>
